services:
  chuchabot:
    image: chuchabot
    container_name: chuchabot
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: .env
    environment:
      TELEGRAM_BOT_API_TOKEN: <token>
      TELEGRAM_BOT_SEND_URL: <url>
    restart: always
